[tool.modal]
name = "dumb-little-reader"
description = "A simple RSS feed reader"
version = "0.1.0"

[build]
command = "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[deploy]
command = "modal deploy"

[env]
required = ["PORT"]

[runtime]
python = "3.9"

[expose]
port = "$PORT"